name: FinTech Online
favicon: null
layout_spectrum: 0.3266477850265801
typography_spectrum: 0.8957444245461375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8876932219136506
  lightness: 0.8273653008509427
  saturation: 0.6344314080197364
  rhythmicContrast: 0.16882464103400707
purpose: []
