name: FinTech Online
favicon: null
layout_spectrum: 0.71761
typography_spectrum: 0.9899644774850458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6533388961106539
  lightness: 0.6769188693724573
  saturation: 0.365917592542246
  rhythmicContrast: 0.38472040998749435
purpose: []
