name: FinTech Online
favicon: null
layout_spectrum: 0.71761
typography_spectrum: 0.9899644774850458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b092c'
    - '#3357ab'
    - '#57b3d8'
    - '#fdfaeb'
    - '#8b715b'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
