name: FinTech Online
favicon: null
layout_spectrum: 0.8666394534520805
typography_spectrum: 0.2943597137928009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03258755919523537
  lightness: 0.3710025188047439
  saturation: 0.33223566343076527
  rhythmicContrast: 0.9351951666176319
purpose: []
