name: FinTech Online
favicon: null
layout_spectrum: 0.31908568809740245
typography_spectrum: 0.6316631869412959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2811617781408131
  lightness: 0.7844303664751351
  saturation: 0.8549993950873613
  rhythmicContrast: 0.5556484854314476
purpose: []
